CREATE TEMPORARY TABLE auth_username_preflight AS
    SELECT LOWER(TRIM(username)) AS username
    FROM users
    WHERE 1 = 0;

ALTER TABLE auth_username_preflight
    MODIFY COLUMN username VARCHAR(100) NOT NULL,
    ADD UNIQUE KEY uk_auth_username_preflight (username);

INSERT INTO auth_username_preflight (username)
    SELECT LOWER(TRIM(username)) FROM users;

DROP TEMPORARY TABLE auth_username_preflight;

CREATE TEMPORARY TABLE auth_user_role_preflight AS
    SELECT user_id FROM user_roles WHERE 1 = 0;

ALTER TABLE auth_user_role_preflight
    MODIFY COLUMN user_id BIGINT NOT NULL,
    ADD UNIQUE KEY uk_auth_user_role_preflight (user_id);

INSERT INTO auth_user_role_preflight (user_id)
    SELECT user_id FROM user_roles;

DROP TEMPORARY TABLE auth_user_role_preflight;

CREATE TEMPORARY TABLE auth_role_code_preflight AS
    SELECT code FROM roles WHERE 1 = 0;

ALTER TABLE auth_role_code_preflight
    MODIFY COLUMN code VARCHAR(50) NOT NULL,
    ADD UNIQUE KEY uk_auth_role_code_preflight (code);

INSERT INTO auth_role_code_preflight (code)
    SELECT code FROM roles WHERE code IS NOT NULL;

DROP TEMPORARY TABLE auth_role_code_preflight;

CREATE TEMPORARY TABLE auth_permission_code_preflight AS
    SELECT code FROM permissions WHERE 1 = 0;

ALTER TABLE auth_permission_code_preflight
    MODIFY COLUMN code VARCHAR(100) NOT NULL,
    ADD UNIQUE KEY uk_auth_permission_code_preflight (code);

INSERT INTO auth_permission_code_preflight (code)
    SELECT code FROM permissions WHERE code IS NOT NULL;

DROP TEMPORARY TABLE auth_permission_code_preflight;

UPDATE users SET username = LOWER(TRIM(username));

ALTER TABLE users
    MODIFY COLUMN username VARCHAR(100) NOT NULL,
    ADD CONSTRAINT uk_users_username UNIQUE (username),
    ADD COLUMN credential_changed_at DATETIME(6) NULL;

ALTER TABLE user_roles
    ADD CONSTRAINT uk_user_roles_user_id UNIQUE (user_id);

ALTER TABLE roles
    MODIFY COLUMN code VARCHAR(50) NOT NULL,
    ADD CONSTRAINT uk_roles_code UNIQUE (code);

ALTER TABLE permissions
    MODIFY COLUMN code VARCHAR(100) NOT NULL,
    ADD CONSTRAINT uk_permissions_code UNIQUE (code);

SET FOREIGN_KEY_CHECKS = 0;

ALTER TABLE users MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE roles MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE permissions MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE apartments MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE residents MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE apartment_memberships MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE vehicle_families MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE vehicle_categories MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE vehicles MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE vehicle_resident_relations MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE cards MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE card_assignments MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE pricing_versions MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE monthly_rates MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE visitor_period_rates MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE visitor_car_rate_rules MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE decision_policy_versions MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE parking_subscriptions MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE gate_stations MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE gate_lanes MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE work_shifts MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE parking_sessions MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE gate_events MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE manual_reviews MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE barrier_actions MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE media_assets MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE resident_media MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE gate_event_media MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE face_templates MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE identity_verifications MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE ai_inference_results MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE charges MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE charge_items MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE payments MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE alerts MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;
ALTER TABLE audit_logs MODIFY COLUMN id BIGINT NOT NULL AUTO_INCREMENT;

SET FOREIGN_KEY_CHECKS = 1;
